config/routes.rb
Cone::Application.routes.draw do
  devise_for :shredders

  match 'confirm' => 'shredders#confirm', :as => :confirm
  match 'doconfirm' => 'shredders#do_confirm', :as => :do_confirm
  match 'greetings/:id' => 'alerts#answer', :as => :answer
  match 'in/:id' => 'alerts#in', :as => :link_alert

  resources :snow_reports
  resources :shredders
  resources :subscriptions
  resources :text_subscriptions, :controller => 'subscriptions'
  resources :voice_subscriptions, :controller => 'subscriptions'

  namespace :api do
    resources :android
    resources :area do
      member do
        get 'last_report'
      end
    end
    resources :passes do
      collection do
        get 'real_time'
        get 'end_of_day'
      end
    end
    resources :ios
    resources :forecast
    resources :sms
  end

  root :to => 'shredders#home'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :area
  belongs_to :shredder
  has_many :alerts
  scope :for_inches_area, lambda{|inches,area_id| where("active = ? and area_id = ? and inches <= ?",true,area_id,inches)}
  validates_presence_of :message
  attr_accessible :area_id, :inches, :message, :active, :intro, :gender, :hour
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_shredder!

  def index 
    @shredder = current_shredder 
  end

  def edit
    @subscription = Subscription.find(params[:id])
    not_found unless @subscription && @subscription.shredder_id == current_shredder.id
  end

  def new
    if request.path.include?('voice_subscription')
      @subscription = VoiceSubscription.new
    else
      @subscription = TextSubscription.new
    end
  end

  def show

  end

  def create
    if request.path.include?('voice_subscription')
      @subscription = current_shredder.voice_subscriptions.new(params[:subscription])
    else
      @subscription = current_shredder.text_subscriptions.new(params[:subscription])
    end
    if @subscription.save
      flash[:notice] = "Your new subscription has been saved"
      redirect_to subscriptions_url
    else
      flash[:error] = "Please correct the errors and try again"
      render :action => :new
    end
  end

  def update
    @subscription = Subscription.find(params[:id])
    not_found unless @subscription && @subscription.shredder_id == current_shredder.id
    @subscription.update_attributes(params[:subscription])
    flash[:notice] = "Updated your subscription #{current_shredder.random_name}!"
    redirect_to subscriptions_url
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    not_found unless @subscription && @subscription.shredder_id == current_shredder.id
    @subscription.destroy
    flash[:notice] = "Deleted your subscription #{current_shredder.random_name}! :( :( :("
    redirect_to subscriptions_url
  end

end

app/views/subscriptions/edit.html.erb
<div class="eight columns">
  <h3>Updating <%= @subscription.description %></h3>
    <%= form_for(@subscription, :as => 'subscription') do |f| %>
      <%= f.label :inches, 'Freshies Threshold:' %>
      <%= f.select :inches, (2..12).collect{|i| ["#{i} or more inches",i]}, {:include_blank => false, :value => @subscription.inches} %>
      <% if @subscription.instance_of?(VoiceSubscription) -%>
      <%= f.label :intro, 'Intro Music' %>
      <%= f.select :intro, VoiceSubscription.intros.collect{|i| ["#{i}",i]}, {:include_blank => true, :value => @subscription.intro} %>
      <%= f.label :gender, 'Voice' %>
      <%= f.select :gender, VoiceSubscription.genders.collect{|i| ["#{i}",i]}, {:include_blank => false, :value => @subscription.gender} %>
      <% end -%>
      <%= f.label :active, 'Subscription Active?:' %>
      <%= f.check_box :active %>
      <%= f.label :message, 'Text Message:' %>
      <%= f.text_area :message, { :cols => 0, :rows => 0, :style => '', :class => 'message', :'data-max' => @subscription.message_length } %>
      <span class="countdown"></span>
      <%= f.submit 'Save Changes' %>
      <a class="button" id="preview">Update Preview</a>
    <% end %>

    <h5>Alert Preview</h5>
    <div id="preview-window"></div>
</div>
<div class="sidebar seven columns offset-by-one">
  <div class="highlight shimmed">
  <h3>Customize Your Alert</h3>
  <p>Now you have real ultimate power!  You can customize your very own text shredder alert.  You could use up your <%= @subscription.message_length %> charachters by telling yourself just how rad you are, or you can use the following widgets to add some real info:</p>
      <ul class="square">
        <li>{{area}}</li>
        <li>{{new_snow}}</li>
        <li>{{base_depth}}</li>
        <li>{{mid_depth}}</li>
        <li>{{base_temp}}</li>
        <li>{{mid_temp}}</li>
        <li>{{summit_temp}}</li>
        <li>{{report_time}}</li>
      </ul>
  <h3>Want to Bail?</h3>
  <p>If you want to remove this alert, just click this crazy large button down below. Keep in mind, there is no way to add a new alert right now... so check yoself before you wreck yoself.</p>
  <%=link_to "Delete Subscription?",subscription_path(@subscription.id), :method => :delete, :class => "danger", :confirm => "Are you sure ?"%>
  </div>
</div>
<script type="text/javascript">
  var demoData = {
    area: '<%= @subscription.area.name %>',
    base_temp: 28,
    mid_temp: 26,
    summit_temp: 24,
    base_depth: 100,
    mid_depth: 120,
    new_snow: 6,
    report_time: '06:15 12-28-11'
  };
</script>

app/views/subscriptions/index.html.erb
<div class="sixteen columns">
  <h3>Manage Your Subscriptions</h3>
</div>
  <% @shredder.subscriptions.each do |subscription| -%>
  <div class="one-third column">
    <div class="alert-notice sub">
      <a href="<%= edit_subscription_url(subscription) %>"><span class="desc"><%= subscription.description %></span>
      <span class="threshold"><%= subscription.inches %>&quot;</span>
      <span class="area">@<%= subscription.area.name %></span></a>
    </div>
  </div>
  <% end -%>
  <div class="one-third column">
    <div class="alert-green sub">
      <a href="<%= new_subscription_path %>"><span class="desc">New Text Alert</span>
      <span class="threshold">+</span>
    </a>
    </div>
  </div>
  <div class="one-third column">
    <div class="alert-green sub">
      <a href="<%= new_voice_subscription_path %>"><span class="desc">New Voice Alert</span>
      <span class="threshold">+</span>
    </a>
    </div>
  </div>

app/views/subscriptions/new.html.erb
<div class="eight columns">
  <% if @subscription.errors.any? %>
    <div class="alert-error">
      <h4>Gaper Alert!</h4>
      <p>Please fix the following errors:</p>
      <ul>
        <% for message in @subscription.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h3>New <%= @subscription.description %></h3>
  <% if @subscription.instance_of?(VoiceSubscription) -%>
  <p>Welcome to the super hot, super beta new feature at conepatrol.com: Voice Alerts!  These work just like the Text Alert, except, instead of sending a text, the robot calls you!</p>
  <p>Yesiree, you get a POWDER WAKE UP CALL.  You can even choose some intro music to get STOKED, and of course you can customize the message and have that sweet robotic voice tell you how awesome you are... because you *are* awesome!</p>
  <% end -%>
    <%= form_for(@subscription, :as => 'subscription') do |f| %>
      <%= f.label :area_id, 'Ski Area:' %>
      <%= f.select :area_id, Area.active.collect{|i| [i.name,i.id]}, {:include_blank => false} %>
      <%= f.label :inches, 'Freshies Threshold:' %>
      <%= f.select :inches, (2..12).collect{|i| ["#{i} or more inches",i]}, {:include_blank => false, :value => @subscription.inches} %>
      <% if @subscription.instance_of?(VoiceSubscription) -%>
      <%= f.label :intro, 'Intro Music' %>
      <%= f.select :intro, VoiceSubscription.intros.collect{|i| ["#{i}",i]}, {:include_blank => true, :value => @subscription.intro} %>
      <%= f.label :gender, 'Voice' %>
      <%= f.select :gender, VoiceSubscription.genders.collect{|i| ["#{i}",i]}, {:include_blank => false, :value => @subscription.gender} %>
      <% end -%>
      <%= f.label :active, 'Subscription Active?:' %>
      <%= f.check_box :active, :checked => true %>
      <%= f.label :message, 'Text Message:' %>
      <%= f.text_area :message, { :cols => 0, :rows => 0, :style => '', :class => 'message', :'data-max' => @subscription.message_length, :value => 'ZOMG FRESHIES! {{area}} recieved {{new_snow}}" and it is {{base_temp}} at the lodge!' } %>
      <span class="countdown"></span>
      <%= f.submit 'Save' %>
      <a class="button" id="preview">Update Preview</a>
    <% end %>

    <h5>Alert Preview</h5>
    <div id="preview-window"></div>
</div>
<div class="sidebar seven columns offset-by-one">
  <div class="highlight shimmed">
  <h3>Customize Your Alert</h3>
  <p>Now you have real ultimate power!  You can customize your very own text shredder alert.  You could use up your <%= @subscription.message_length %> charachters by telling yourself just how rad you are, or you can use the following widgets to add some real info:</p>
      <ul class="square">
        <li>{{area}}</li>
        <li>{{new_snow}}</li>
        <li>{{base_depth}}</li>
        <li>{{mid_depth}}</li>
        <li>{{base_temp}}</li>
        <li>{{mid_temp}}</li>
        <li>{{summit_temp}}</li>
        <li>{{report_time}}</li>
      </ul>
  </div>
</div>
<script type="text/javascript">
  var demoData = {
    area: 'Resort Name',
    base_temp: 28,
    mid_temp: 26,
    summit_temp: 24,
    base_depth: 100,
    mid_depth: 120,
    new_snow: 6,
    report_time: '06:15 12-28-11'
  };
</script>